# Generated by Django 5.0.1 on 2024-02-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="preposition",
            new_name="article",
        ),
    ]
