# Generated by Django 5.0.1 on 2024-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0004_result_one_result_per_word_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="english",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="word",
            name="polish",
            field=models.CharField(default="", max_length=100),
        ),
    ]
