# Generated by Django 5.0.1 on 2024-02-20 15:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0007_alter_generatortask_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatortask",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
