# Generated by Django 5.0.1 on 2024-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0008_generatortask_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatortask",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
