# Generated by Django 5.0.1 on 2024-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0009_alter_generatortask_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="article",
            field=models.CharField(
                blank=True,
                choices=[("DER", "der"), ("DIE", "die"), ("DAS", "das")],
                default="DER",
                max_length=3,
                null=True,
            ),
        ),
    ]
