version: '3.9'
name: tolle-karten-back
services:
  app:
    build:
      context: ../../../
      dockerfile: ./src/deployment/local/Dockerfile
    container_name: "tolle-karten-app"
    volumes:
      - app-data:/app/
      - static:/app/static
      - media:/app/media/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=tkbproj.settings.development
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_HOST=tolle-karten-db
      - DB_DB=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
    depends_on:
        redis:
          condition: service_started
        db:
          condition: service_started
  redis:
    image: "redis:latest"
    container_name: "tolle-karten-redis"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    container_name: "tolle-karten-db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data/:Z
    ports:
      - "5432:5432"

volumes:
  app-data:
  static:
  media:
  redis-data:
  db-data:
